apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordconverter-deployment
  labels:
    app: wordconverter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordconverter
  template:
    metadata:
      labels:
        app: wordconverter
    spec:
      containers:
      - name: wordconverter
        image: wordcoverter:latest  # Your Docker registry name
        ports:
        - containerPort: 80
